name: ngseq_quality_visualisation

dependencies:
  - python=3.9
  - numpy
  - pandas
  - plotly
  - dash
  - pip
  - pip:
    - fastqcparser
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
